"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, …

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""


Start=1
Sum = 2
Pre=2
New=0
while New<4000000:
    New=Start+Pre
    if New%2==0:
        Sum=Sum+New
    else:
        pass
    Start=Pre
    Pre=New

print(Sum)

""" output:
4613732
"""